### ISSUE TITLE
[ACE] (interact_menu) ERROR: Failed to add action

### ISSUE THREAD

**Issue by archie-archibald** [KyklopCZ/Kyklop_EW#10]
I've loaded the mod plus the ACE & CBA3 dependencies. I start a new mission in the editor, place a UAV operator, and start the mission.

ACE menu is missing the EW actions.

Checked the logs, found a bunch of errors like this:

[ACE] (interact_menu) ERROR: Failed to add action - action (Check jammer state) to parent ["ACE_SelfActions","Jamming"] on object B_soldier_UAV_06_F [1]

Including the full log file below

[Arma3_x64_2020-10-02_21-04-24.zip](https://github.com/KyklopCZ/Kyklop_EW/files/5320862/Arma3_x64_2020-10-02_21-04-24.zip)

**Comment by KyklopCZ** [comment]
I've looked into the issue and I may have found your problem. If you don't have a jammer backpack equipped, you obviously can't see the EW actions. Try to equip a valid jammer backpack (like Contact DLC radio) first and then search for the EW action. As for the errors in the log, I have no idea what could be causing those as they don't appear on my side when I repeat what you did.

**Comment by archie-archibald** [comment]
Thanks, I see what the issue is. I equipped the regular UAV terminal backpack instead of the CUP version, my mistake.

I did some more testing and everything works except the RHS GAZ-66 (R-142). I filed https://github.com/KyklopCZ/Kyklop_EW/issues/15
