### ISSUE TITLE
More fighters to be added EW features suggestion

### ISSUE THREAD

**Issue by acknowledge14** [KyklopCZ/Kyklop_EW#11]
F-23A
https://steamcommunity.com/sharedfiles/filedetails/?id=1384712753

F-38C Peregrine in Aegis mod (a fictional 5th generation stealth fighter mass produced throughout the world)
https://steamcommunity.com/sharedfiles/filedetails/?id=949252631&searchtext=

FC-37 Thunder
https://steamcommunity.com/sharedfiles/filedetails/?id=330990595&searchtext=
https://steamcommunity.com/linkfilter/?url=https://forums.bistudio.com/forums/topic/193772-fc-37-fa-35e-restorationjetsdlc-update-wip/

SU-50  in RHSAFRF mod

J-20 in VME PLA mod
https://steamcommunity.com/sharedfiles/filedetails/?id=1562282342&searchtext=vme+pla

**Comment by KyklopCZ** [comment]
You can add them yourself, that's why I designed my mod in easily customizable way. Documentation is available on Steam Workshop page or [here](https://docs.google.com/document/d/1Fvk_VtttAVX44SxvQOk-3OiN7bPTe-nouBsxWke7oA4/edit?usp=sharing). I won't add them though.
