### ISSUE TITLE
[SUGGESTION] Remove irrelevant jammers from Jammer Status Report

### ISSUE THREAD

**Issue by AVESUM** [KyklopCZ/Kyklop_EW#12]
**Suggestion:**
To improve immersion and reduce cluttering irrelevant jammers is suggested to be excluded from players UI. 
As an example a backpack (if configured by mission maker as such) shouldn't have the capacity to jam radars or drones and these types of jamming is then also hidden for the player. 

**Practical implementation:**
All jammers with disabled jammers (0) is hidden in UI for that specific j;ammer. The following init will only show Radio, GSM and RF whilst the other types of jamming are hidden as the user turns on, scans and detects the different jammer categories: 
["my_tactical_backpack_jammer", 1, [0,200,200,200,0,0,0,1,1]] call kyk_ew_fnc_jammerAdd;

**Comment by KyklopCZ** [comment]
That's a brilliant idea. In fact it's so brilliant that my mod already has this feature :)

**Comment by AVESUM** [comment]
It's the players UI visible in the image below which is suggested :)

https://imgur.com/1ElBCDw
In this instance the vehicle is configured 
`["sfp_tgb16_ksp58", 2, [0,500,500,500,500,500,0,1,1]] call kyk_ew_fnc_jammerAdd;`
and the **Radar** in this view should not be visible at all, not even red. 
IE remove TYPE, STATUS and RANGE in this view for disabled jammer types. 

This is even more prominent if the player carries a backpack configured with only one type of jammer.

**Comment by KyklopCZ** [comment]
Oh you meant the jammer status report, I assumed you meant the ACE interaction menu items. My fault.
