### ISSUE TITLE
[QUESTION] Converting standard ACE IED to jammable?

### ISSUE THREAD

**Issue by AVESUM** [KyklopCZ/Kyklop_EW#13]
I am unsuccessful in converting Zeus placed ACE IEDs to jammable. Should I do something differently?

defineJammers.sqf:
```
if(isServer) then
{
   waitUntil {kyk_ew_initComplete};
   call kyk_ew_fnc_removeAllJammers;
   ["sfp_tgb16_ksp58", 2, [0,500,500,500,500,500,0,1,1]] call kyk_ew_fnc_jammerAdd;
   ["PressurePlate", [3, 1, "Radio detonator"]] call kyk_ew_fnc_clackerAdd;
};
```
**Result:**
ACE IED detonates if player is close even with RfJammer on.

**Expected result:**
ACE IEDs placed with ZEN or ALiVE is standard PreassurePlate but with above init they simulate a RfDetonated IED and as such is jammable and give the player a hint that the Rf trigger was jammed.

**Ways to reproduce:**
Local MP Zeus, IED placed in Zeus Enhanced. Vehicle with RfJammer activated. Drive over IED.

**Comment by KyklopCZ** [comment]
I recreated the problem and discovered that ACE doesn't call the eventhandler I use to block the detonation, when the explosive is detonated by a sensor like pressure plate. I updated the documentation and mod description to reflect this fact.

**Comment by KyklopCZ** [comment]
I will do some research whether it is possible to jam explosives like those. If yes, then I will try to implement it and therefore mark this as "Improvement". If not, I'll mark this as "wontfix" and close.
