### ISSUE TITLE
RHS GAZ-66 (R-142) not working

### ISSUE THREAD

**Issue by archie-archibald** [KyklopCZ/Kyklop_EW#15]
I created a test mission with all of the different GAZ-66 R-142s (rhs_gaz66_r142_msv, rhs_gaz66_r142_vdv, rhs_gaz66_r142_vmf, rhs_gaz66_r142_vv) and don't see the EW ace menu option in any of them.

Next I tried to use a script to define the jammers manually like so:

```
if(isServer) then
{
	waitUntil {kyk_ew_initComplete};
	
	call kyk_ew_fnc_removeAllJammers;
	
	["rhs_gaz66_msv", 1, [0,200,200,100,0,0,0,1,1]] call kyk_ew_fnc_jammerAdd;
	["rhs_tigr_msv", 1, [0,200,200,100,0,0,0,1,1]] call kyk_ew_fnc_jammerAdd;
	["rhs_gaz66_r142_msv", 1, [0,200,200,100,0,0,0,1,1]] call kyk_ew_fnc_jammerAdd;
};
```

The first two work fine (rhs_gaz66_msv, rhs_gaz66_r142_msv) but r142 doesn't.

I looked through the logs and couldn't find anything related to this, there are no errors.

**Comment by KyklopCZ** [comment]
That's intended behaviour. R-142 has to have it's mast extended for the EW actions to appear. Also all of the jammers are disabled automatically once the mast is retracted.

**Comment by archie-archibald** [comment]
I see, that makes sense.

Everything works except for the BLUFOR CDF Gaz-66 R-142

The class name is rhsgref_cdf_b_gaz66_r142 and it's missing from the rhsgref_main config in fn_jammerDefinition.sqf

Created PR - https://github.com/KyklopCZ/Kyklop_EW/pull/17
