### ISSUE TITLE
Error during init, radar successfully jammed but radar is not restored once jamming is deactivated

### ISSUE THREAD

**Issue by archie-archibald** [KyklopCZ/Kyklop_EW#20]
During scenario initialization the following error occurs:
![20201015132215_1](https://user-images.githubusercontent.com/69365529/96166573-24f46800-0eec-11eb-9866-efb826d25105.jpg)

Steps to reproduce:

1. Place SAM site and jammer
2. Activate jammer
3. Radar on SAM site is successfully disabled
4. Deactivate jammer
5. Radar on SAM site still disabled

**Comment by KyklopCZ** [comment]
Yeah, so... this is what happens when you work on different projects and use different languages for them and just assume that the language you're using currently knows the command that every other language you use knows :)

**Comment by KyklopCZ** [comment]
Reopened because I want to make sure that the radar gets restored after jamming is disabled, which may be unrelated to the hotfix I've done with the last pull request.

**Comment by archie-archibald** [comment]
thanks for working on this, it's a really cool mod and I look forward to using it in missions

**Comment by KyklopCZ** [comment]
Yeah, it's kinda my responsibility so no need to thank me, if anything you should b*tch on me for making such simple mistakes that break the whole mod and then updating it without properly testing it :). Anyway I plan to do a bit of testing tomorrow and then push the update out ASAP.
