### ISSUE TITLE
[Enhancement request] Incorporate CBA_A3

### ISSUE THREAD

**Issue by YetheSamartaka** [KyklopCZ/Kyklop_EW#25]
Incorporate CBA_A3 in your mod. Migrate some settings and inits to the CBA. Many parts of your code could be improved by CBA functions that would also increase performance and efficiency + it would add more options to expand.

**Comment by KyklopCZ** [comment]
I don't see which parts could be improved by CBA functions. When briefly going through a list of all CBA functions I didn't come across any functions that would optimize or simplify my code, at least not noticably. As for the settings, I, again, don't see which settings could be set through CBA as basically the only settings that come to my mind now are jammer definitions that would be very impractical to do in CBA settings.

**Comment by YetheSamartaka** [comment]
When going through the code again, I agree, maybe the CBA_fnc_serverEvent, CBA_fnc_globalEvent, CBA_fnc_localEvent or CBA_fnc_targetEvent could be used or some EHs or CBA_fnc_simplifyAngle. What I've particularly meant was to move from mission file based **defineJammers** and have people to define it in addon options (and also cba_settings) which you would define it XEH_preInit.sqf and there would be those options - nice and easy.

What crossed my mind and I'm not sure if I should create another feature request (I don't want to spam) is to utilize Module_F. Basically create simple Zeus (or even for editor) that could be placed down and it would have settings for jammers. It could be applied to objecs and also another module to remove it if applied to object. Currently it is not that user friendly and this module solution would be very elegant, more people could use this addon.

**Comment by KyklopCZ** [comment]
I will look into those modules as control of jammer via Zeus modules is one of my planned features. As for the addon options, I think that it would be quite impractical, especially if bigger amount of platforms would need to be defined as jammers. In my opinion, doing the definitions in a file is more comfortable than doing them in a somewhat cramped interface in Arma. I also consider the current approach of defining the platforms and properties in the mission file to be better for the purpose of my mod, as it gives the mission maker the most control over the jamming-capable platforms which is, in my opinion, a good thing as which platforms are jamming-capable should ultimately be decided by the mission.

**Comment by YetheSamartaka** [comment]
Okay, I see your point, thank you for answers, that will be probably all from me on this topic, looking forward to that module feature 👍🏻
