### ISSUE TITLE
Please do an example.

### ISSUE THREAD

**Issue by PREACHERER** [KyklopCZ/Kyklop_EW#9]
For the init section of actually putting the script in-game, you should add in an example script of what the finished script should look like. For guys who are new to scripting, it would help a lot to know what it should actually look like for it to work in-game. This example could be thrown into the document you made or just the steam page. Or even a short youtube video going through the process.

**Comment by KyklopCZ** [comment]
There is an example, both in the documentation AND on the steam page and it's under [this](https://drive.google.com/file/d/1RP60zlWSwysb6Z4TI7ywwsP3RXgOf4Vs/view) link. If you actually open the sqf files you can see the code and I think that using the documentation and this example any person should be able to figure out how to write own custom configuration. And just to be sure that you know, this is only necessary if you want a custom jammer configuration. You can use the mod without any setup at all.
